### ISSUE TITLE
Using globs for `directory` is slow

### ISSUE THREAD

**Issue by freshollie** [rx-ts/eslint-import-resolver-ts#12]
The recommended config for multiple directories is very slow (`./packages/**/tsconfig.json`)

This is probably due to the library walking the `node_modules` directories? Would it be possible to ignore the `node_modules` folders?

For now, I recommend explicit levels in the directories glob, which is much faster.

```
"settings": {
    "import/resolver": {
    "ts": {
      "directory": "./*/*/tsconfig.json" // Any package, but don't go deeper than the package root
    }
  }
```

**Comment by JounQin** [comment]
@freshollie Sorry I didn't notice this issue previous, I'll take a look ASAP.

**Comment by JounQin** [comment]
@Teoxoy Would you like to help with this?

**Comment by teoxoy** [comment]
`./packages/**/tsconfig.json` shouldn't look in the `node_modules` folder.

Having said that, the example glob can be optimized like this: `./packages/*/tsconfig.json` - this way the star (*) will only match one layer deep instead of the globstar (**) matching n layers

@freshollie can you test the proposed glob and see if it's faster?

If it is, we should update the readme.

**Comment by JounQin** [comment]
@Teoxoy Should directory matched in `node_modules` be ignored always? What means we can use `glob.sync(pattern, { ignore: 'node_modules' })`.

**Comment by teoxoy** [comment]
`ignore` should only be used when the `pattern` would include a path that then `ignore` will remove.

Using it in our case, will make things slower and with no real benefits since `./packages/*/tsconfig.json` will not match anything inside `node_modules`.

As I said above, the issue was that I used a globstar instead of a star for the example.

**Comment by JounQin** [comment]
@Teoxoy Thanks for clarifying. Maybe another stupid question, should we replace `glob` with `tiny-glob` according to its [benchmark](https://github.com/terkelg/tiny-glob#benchmarks)?

**Comment by JounQin** [comment]
@freshollie v0.4.0 has been released.

**Comment by freshollie** [comment]
Hey @JounQin, thanks for this, updating now.

@Teoxoy, yes, using the single star glob was always faster. I had already discovered this before posting the issue, so I was more trying to inform that using ** would make eslint very slow and that having it in the readme was a bad idea.

**Comment by JounQin** [comment]
@freshollie Yep, we've changed `**` to `*` in README, thanks for reporting any way.
