### ISSUE TITLE
What makes this package different from the original one?

### ISSUE THREAD

**Issue by rfgamaral** [rx-ts/eslint-import-resolver-ts#15]
This is a fork of [`alexgorbatchev/eslint-import-resolver-typescript`](https://github.com/alexgorbatchev/eslint-import-resolver-typescript) and no where in the README is explained the reasoning for creating and using this instead of the original module.

Would it be possible for you to explain what are the pros and cons of using this versus the original module? I'm just trying to make an informed decision :)

**Comment by JounQin** [comment]
@rfgamaral Sorry I didn't notice about this issue previous, it does be a fork of the original one. It is created because the original author disappeared for months and a several PR are blocked. So I forked it and publish it as a new package.

And the original author returned, I PR backed to it then. So it should be exactly same now. You should use the original one always which I'm a maintainer also now.

This one could be an experimental resolver with other new features for my own.
